### ISSUE TITLE
"Invalid value for network "test" option "parent": Required value" (incus)

### ISSUE THREAD

**Issue by marcus-j-davies** [PenningLabs/lxconsole#11]
Hello,

Before I begin, this is great work - kudos to you!
I was using your php version, but seems to not support `incus`

so switched to the python version
This maybe `incus` related (I think more users will be making the switch)

But adding a `macvlan`, I get the below.

![Screenshot 2024-01-08 at 20 48 08](https://github.com/PenningLabs/lxconsole/assets/55892693/9a004a5e-5bb0-4800-b381-1d0c49cc9693)

via cli is fine:

**Attached to vLan 30**
```
root@rpi5:~# incus network create vLan30 --type macvlan parent=eth0 vlan=30
Network vLan30 created
root@rpi5:~# 
```
**Attached to Native Network**
```
root@rpi5:~# incus network create Native --type macvlan parent=eth0
Network Native created
root@rpi5:~# 
```

**Comment by matthewalanpenning** [comment]
Thanks for finding this. I found the issue in my code when creating the network and it affects both incus and lxd. I will get this patched and out in the next update.

**Comment by matthewalanpenning** [comment]
Just pushed version 0.4.3 and it should take care of the issue.
