### ISSUE TITLE
Server stalls after a while

### ISSUE THREAD

**Issue by pazos** [PenningLabs/lxconsole#12]
Hi. I've migrated from lxd/lxdware dashboard to incus/lxconsole on an arch hipervisor.

I installed an isolated python environment in `/cache/lxconsole/env` and git cloned this repo in `/cache/lxconsole/repo`.

Here's the systemd unit I'm using to manage the service

```bash
[Unit]
Description=Lxconsole

[Service]
Type=simple
StandardOutput=journal
WorkingDirectory=/cache/lxconsole/repo
ExecStart=/cache/lxconsole/env/bin/python run.py
Restart=on-failure
RestartSec=1s

[Install]
WantedBy=default.target
```

After a while, a few hours?, the server stops to respond on port 5000. 

Looking at the logs it seems the server is still running

```
ene 16 01:13:22 terra systemd[179023]: Started Lxconsole.
ene 16 01:13:23 terra python[180036]:  * Serving Flask app 'lxconsole'
ene 16 01:13:23 terra python[180036]:  * Debug mode: off
ene 16 01:13:23 terra python[180036]: WARNING: This is a development server. Do not use it in a pro>
ene 16 01:13:23 terra python[180036]:  * Running on all addresses (0.0.0.0)
ene 16 01:13:23 terra python[180036]:  * Running on http://127.0.0.1:5000
ene 16 01:13:23 terra python[180036]:  * Running on http://192.168.1.254:5000
ene 16 01:13:23 terra python[180036]: Press CTRL+C to quit
```

**Comment by matthewalanpenning** [comment]
I have a very similar setup but on an Ubuntu server without issues. I will install it in an Arch lxc container and see if I can replicate the issue.

**Comment by pazos** [comment]
I'm going to close it since I'm not able to reproduce anymore. Thanks for your time!
