### ISSUE TITLE
sqlite issue?

### ISSUE THREAD

**Issue by tpsailer** [PenningLabs/lxconsole#14]
Just getting back to this project after many months, spun up a new container, installed according to the Readme via pip.

I'm assuming that sqlite3 needs to be installed and running? I'm not remembering, and I can't find it in any docs, but sqlite3 is referenced in the code.

I'm unable to do anything as I keep getting the popup:

DataTables warning: table id=myDataTable - not authorized

No errors in the console logging.

**Comment by tpsailer** [comment]
OK, did that too fast. I'm sounding like a user... :(

Ubuntu 22.04, lxd snap 5.20, Ubuntu 22.04 container, git clone the latest on 2/28

**Comment by matthewalanpenning** [comment]
I does use sqlite but installs the required packages through the python requirements. The "not authorized" is indicating that your user account does not have the authorization to make the api request in the lxconsole code. Is this happening on all pages?

**Comment by tpsailer** [comment]
As soon as I log in:
 * Serving Flask app 'lxconsole'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.59.169.154:5000
Press CTRL+C to quit
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /register HTTP/1.1" 302 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/css/fonts/source_sans_pro.css HTTP/1.1" 200 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/css/fontawesome-free/css/all.min.css HTTP/1.1" 200 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/css/bootstrap/bootstrap-5.2.3.min.css HTTP/1.1" 200 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/css/datatables/dataTables.bootstrap5.min.css HTTP/1.1" 200 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/dist/css/adminlte.min.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/js/popper/popper.min.js HTTP/1.1" 200 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/js/bootstrap/bootstrap-5.2.3.bundle.min.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/js/jquery/jquery-3.7.1.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/js/datatables/dataTables.bootstrap5.min.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/js/datatables/jquery.dataTables-1.13.6.min.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/js/jquery-knob/jquery.knob.min.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/dist/js/adminlte.min.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/js/sidebar.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/assets/img/logo-light.svg HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:03] "GET /static/assets/img/logo-bg.svg HTTP/1.1" 200 -
[UserGroup('1', '1')]
UserGroup('1', '1')
1
[]
127.0.0.1 - - [29/Feb/2024 16:16:25] "POST /login HTTP/1.1" 302 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /servers HTTP/1.1" 200 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/css/fonts/source_sans_pro.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/css/datatables/dataTables.bootstrap5.min.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/css/bootstrap/bootstrap-5.2.3.min.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/css/fontawesome-free/css/all.min.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/dist/css/adminlte.min.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/js/bootstrap/bootstrap-5.2.3.bundle.min.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/css/styles.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/js/datatables/jquery.dataTables-1.13.6.min.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/js/jquery/jquery-3.7.1.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/js/datatables/dataTables.bootstrap5.min.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/js/jquery-knob/jquery.knob.min.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/js/sidebar.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/css/xterm/xterm.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/dist/js/adminlte.min.js HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/css/selectize/selectize.default.min.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Feb/2024 16:16:25] "GET /static/assets/img/logo-dark.svg HTTP/1.1" 200 -
127.0.0.1 - - [29/Feb/2024 16:16:26] "GET /static/css/fontawesome-free/webfonts/fa-solid-900.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [29/Feb/2024 16:16:26] "GET /api/servers/list_servers?_=1709223367473 HTTP/1.1" 200 -

**Comment by tpsailer** [comment]
I deleted the container multiple times, set it all back up over and over again, same results.
Until:
I used the default MS browser to add my user, and now all is working fine. I had been using the latest Chrome and FIrefox, so this may be a browser issue. I'll keep trying to narrow it down.
