### ISSUE TITLE
Can't get a list of instances (vms) if one or more are reporting an error.

### ISSUE THREAD

**Issue by pazos** [PenningLabs/lxconsole#22]
Steps to reproduce.

1. ArchLinux host w/ incus 6.1 (affected by https://discuss.linuxcontainers.org/t/stopped-instances-report-state-error/20004) 
2. Stop a VM.
3. Try to get a list of virtual machines under "Instances"

Expected results: a list of running and error instances (like in `incus list`)

Result:
![Captura desde 2024-05-22 22-34-14](https://github.com/PenningLabs/lxconsole/assets/975883/51b3fc83-b2a9-4716-a03a-ad396108ef71)

```
pazos@terra ~> incus list
+-----------+---------+------------------------+------+-----------------+-----------+
|   NAME    |  STATE  |          IPV4          | IPV6 |      TYPE       | SNAPSHOTS |
+-----------+---------+------------------------+------+-----------------+-----------+
| debian    | ERROR   |                        |      | VIRTUAL-MACHINE | 0         |
+-----------+---------+------------------------+------+-----------------+-----------+
```

**Comment by pazos** [comment]
> @pazos Interesting. Is the ERROR state something that happens to all VMs in Arch with Incus 6.1? I am trying to figure out how to recreate the ERROR state to see what is going.

Yup, they work perfectly fine when they're running but show `ERROR` when they're stopped.

It should be easy to reproduce or Arch:

```bash
incus init --vm --empty whatever
incus list whatever
+----------+-------+------+------+-----------------+-----------+
|   NAME   | STATE | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+----------+-------+------+------+-----------------+-----------+
| whatever | ERROR |      |      | VIRTUAL-MACHINE | 0         |
+----------+-------+------+------+-----------------+-----------+
```

**Comment by matthewalanpenning** [comment]
Thanks. I was able to recreate in Arch. I found the issue in my code and will have a patch out hopefully this weekend in v0.5.3.

**Comment by matthewalanpenning** [comment]
Just pushed the v0.5.3 update. I also added the ability to start your instance from the Error state too to get it back running.

**Comment by pazos** [comment]
Thank you!

Works perfectly.
