### ISSUE TITLE
 [FEATURE REQUEST] Make the "Show X entries" selection persistant

### ISSUE THREAD

**Issue by agenciesunited** [PenningLabs/lxconsole#23]
That's generally it. Or create a setting of a default number.

With a large number of containers the list changes back to 10 entries upon return or page reload making it necessary to jump to a certain page or select the number of entries again.

Making the change persistant could save some clicks.

Thanks :-)

Magnus

**Comment by agenciesunited** [comment]
Already done in  Version 0.5.5  :-)

Thanks!

**Comment by matthewalanpenning** [comment]
Magnus,

Yes, I added the persistent storage for the instances page. I am planning to do the same for all the other pages as well, but wanted to at least get this page done first.

Thanks for the suggestion on this.

Matt
